apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditrack-deployment
  labels:
    app: meditrack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meditrack
  template:
    metadata:
      labels:
        app: meditrack
    spec:
      containers:
      - name: meditrack
        image: yourusername/meditrack:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: meditrack-config
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi